"""Authenticated, bounded V1 relay primitives."""

from .admission import (
    MAX_WS_MESSAGE_BYTES,
    AdmissionResult,
    admit_frame,
    offer_to_input_slot,
    reject_frame,
)
from .auth import (
    AuthResult,
    SecretHash,
    Side,
    authorize_join,
    generate_secret,
    hash_secret,
    validate_secret,
    validate_side,
    verify_secret,
)
from .errors import (
    CLOSE_BAD_SECRET,
    CLOSE_DUPLICATE_SIDE,
    CLOSE_JOIN_TIMEOUT,
    CLOSE_MALFORMED_JOIN,
    CLOSE_OUTPUT_TIMEOUT,
    CLOSE_PROTOCOL_VIOLATION,
    CLOSE_REPLACED,
    CLOSE_SESSION_FULL,
    InvalidFrameError,
    RelayError,
    RelayErrorCode,
)
from .fanout import Fanout, FetchDecision
from .sessions import (
    ClientState,
    JoinResult,
    RelayStreamState,
    Session,
    SessionRegistry,
    SessionView,
)
from .streams import (
    STREAM_NAMESPACE,
    assert_stream_owner,
    derive_incoming_stream,
    derive_upload_stream,
    destination_side,
)
from .websocket import (
    JoinMessage,
    RelayService,
    WriteResult,
    read_binary_frame,
    read_join_message,
    send_ready,
    websocket_endpoint,
    write_binary_frame,
)
from .workers import (
    PostgresFrameFetcher,
    PostgresFrameWriter,
    run_fetch_worker,
    run_insert_worker,
    run_output_worker,
)

__all__ = [
    "AdmissionResult",
    "AuthResult",
    "CLOSE_BAD_SECRET",
    "CLOSE_DUPLICATE_SIDE",
    "CLOSE_JOIN_TIMEOUT",
    "CLOSE_MALFORMED_JOIN",
    "CLOSE_OUTPUT_TIMEOUT",
    "CLOSE_PROTOCOL_VIOLATION",
    "CLOSE_REPLACED",
    "CLOSE_SESSION_FULL",
    "ClientState",
    "Fanout",
    "FetchDecision",
    "JoinMessage",
    "JoinResult",
    "InvalidFrameError",
    "MAX_WS_MESSAGE_BYTES",
    "PostgresFrameFetcher",
    "PostgresFrameWriter",
    "RelayError",
    "RelayErrorCode",
    "RelayService",
    "RelayStreamState",
    "SecretHash",
    "Session",
    "SessionRegistry",
    "SessionView",
    "Side",
    "STREAM_NAMESPACE",
    "WriteResult",
    "admit_frame",
    "assert_stream_owner",
    "authorize_join",
    "destination_side",
    "derive_incoming_stream",
    "derive_upload_stream",
    "generate_secret",
    "hash_secret",
    "offer_to_input_slot",
    "read_binary_frame",
    "read_join_message",
    "reject_frame",
    "run_fetch_worker",
    "run_insert_worker",
    "run_output_worker",
    "send_ready",
    "validate_secret",
    "validate_side",
    "verify_secret",
    "websocket_endpoint",
    "write_binary_frame",
]
